name: frontend
description: "Smart Task App"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  auto_route: ^10.1.0+1
  shared_preferences: ^2.5.3
  auto_route_generator: ^10.1.0
  provider: ^6.1.5
  flutter_localization: ^0.3.2
  flutter_gen: ^5.10.0
  flutter_dotenv: ^5.2.1
  intl: ^0.19.0
  toggle_switch: ^2.3.0
  percent_indicator: ^4.2.5
  dio: ^5.8.0+1
  json_annotation: ^4.9.0
  flutter_otp_text_field: ^1.5.1+1
  dropdown_search: ^5.0.6
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  fl_chart: ^1.0.0
  animated_text_kit: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true

  generate: true

  assets:
    - .env
    - assets/images/
    - assets/icons/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
